device: 0
data_dir: /data/
resolution_training: 1

# Validation and test indexing from data_files - rest is assumed to be training
val_set: [0]
test_set: [1]

# ROI Mask paths & atlas -> set to null if not available
mask_heart: /data/mask_heart
mask_thorax: /data/mask_thorax
atlas: /data/atlas

# Dataset file definitions
data_files:
  - folder: E0000013
    volume: stic
    image_2d: std-views
    PE_2D: [0, 0,  1, 2, 2, 3, 3]

  - folder: E0000014
    volume: stic
    image_2d: std-views
    PE_2D: [0, 0,  0, 2, 2, 3, 3]
